---
services:
  db:
    image: "mysql:8"
    command: --max_allowed_packet=67108864
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
